# Generated by Django 2.1.3 on 2018-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tiempo_fin',
            field=models.TimeField(null=True, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tiempo_ini',
            field=models.TimeField(null=True, verbose_name='inicio'),
        ),
    ]
